name: 'dbt_finance'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +dbt_finance:
    bronze:
      +materialized: view
    silver:
      +materialized: incremental
      +schema: SILVER
      +on_schema_change: sync_all_columns
    gold:
      +materialized: incremental
      +schema: GOLD
      +on_schema_change: sync_all_columns

snapshots:
  +dbt_finance:
    +schema: GOLD
