
name: 'cbre_company_hub'
version: '1.0.0'
config-version: 2

profile: 'default'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Build artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cbre_company_hub:
    +database: GDP_CLIENT_DB    
    sources:
      +database: GDP_CLIENT_DB
      +schema: BRONZE
      +materialized: view
    staging:
      +database: GDP_CLIENT_DB
      +schema: STG
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: sync_all_columns





