
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
sources:
  - name: Property
    database: GDP_PROPERTY_DB
    schema: STG
    tables:
      - name: property

  - name: Broker
    database: GDP_BROKER_DB
    schema: STG
    tables:
      - name: property 

  - name: Property_dynamic
    database: "{{ var('var_database_name') }}"
    schema: "{{ var('var_schema_name') }}"
    tables:
      - name: property

  - name: Config
    database: GDP_PROPERTY_DB
    schema: CONFIG
    tables:
      - name: MODEL_CONFIG

